name: Exercise_07
on:
  push:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: npm ci

      - name: Test (Node v${{ matrix.node }})
        run: npm test
  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: npm ci
      
      - name: Build Project
        run: npm run build

      - name: Upload Dist Folder
        uses: actions/upload-artifact@v4
        with:
          name: node-app-build-v${{ matrix.node }}
          path: ./dist
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME_SRICHARAN4444 }}
          password: ${{ secrets.DOCKER_PASSWORD_SRICHARAN4444 }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app-build-v18
          path: ./build

      - name: Build Docker image
        working-directory: .
        run: |
          docker build -t node-artifact-demo-v18 .

      - name: Push Docker image to Docker Hub
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME_SRICHARAN4444 }}/node-artifact-demo-v18
          docker tag node-artifact-demo-v18:latest $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest
  deploy:
    needs: docker
    runs-on: ubuntu-latest
    environment: "!e ${{ github.ref_name }}==main? production: ${{ github.ref_name }}==dev? development: development"
    steps:
      - name: PRINT ENV VARIABLES
        run: |
          echo "API_URL: ${{ vars.API_URL }}"
          echo "DB_NAME: ${{ vars.DB_NAME }}"